kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: redis
spec:
  ports:
    # Accept traffic sent to port 6379
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    env: dev
    app: vote
    role: redis
  type: NodePort