apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    env: dev
    app: vote
    role: web
spec:
  containers:
  - image: 514374710223.dkr.ecr.ap-southeast-2.amazonaws.com/kubevote:latest
    name: kubevote
